### PR TITLE
Replace `usize` pointers in `Decoder` with `*const u8`

### PR DESCRIPTION
**Pull request by clubby789**
Uses explicit pointers instead of integers, which should help identify issues like #323

### CODE REVIEW

**Comment by wtfsck** [comment]
I don't like this PR. It's only there to stop clippy from suggesting that some fn can be const. Also, I believe there's a UB in the code that calls ptr::add() since the docs say that the result must be within the allocated region or one byte past it, but eg. `ptr.add(4)` could be 2+ bytes past the end of the slice.

https://doc.rust-lang.org/std/primitive.pointer.html#method.add

"Both the starting and resulting pointer must be either in bounds or one byte past the end of the same allocated object."

**Comment by wtfsck** [comment]
Adding an attribute to tell clippy to ignore that lint is better and only a one-line change.

**Comment by clubby789** [comment]
That issue was what prompted this change, but I believe using raw pointers explicitly is better than using `usize` as a hack to get around `Send+Sync` bounds, as it also allows tools like `Miri` to identify pointer UB.

> Also, I believe there's a UB in the code that calls `ptr::add()`
Which part? As far as I can tell I've used semantically equivalent operations everywhere, and (although the entire test suite takes far too long under miri to test fully) running a few relevant tests reports no UB.

**Comment by Nilstrieb** [comment]
Casting integers to pointers is bad practice and should be avoided if possible. It severely limits the ability of tools such as Miri to find undefined behavior. It can also make code harder to read, as the reader usually expects integers to be integers and not hidden pointers. If possible (and in pure Rust code, it basically always is), code should follow the strict provenance rules and never cast an integer to a pointer.

**Comment by wtfsck** [comment]
I've added `#[allow(clippy::missing_const_for_fn)]` to that fn, so I'll close this PR.

**Comment by wtfsck** [comment]
> > Also, I believe there's a UB in the code that calls `ptr::add()`
> 
> Which part? As far as I can tell I've used semantically equivalent operations everywhere, and (although the entire test suite takes far too long under miri to test fully) running a few relevant tests reports no UB.

If we're already at the end of the data then ptr.add(1) will be 2 bytes past the end which is UB. If it's a usize, that can't happen.

**Pull request closed without merging**
