### PR TITLE
Add try_immediate() to the API docs

### PR DESCRIPTION
**Pull request by mbbutler**
This PR adds `try_immediate()` to the API docs by adding documentation for the function and removing its `#[doc(hidden)]` attribute.

### CODE REVIEW

**Comment by wtfsck** [comment]
Build failed because of some extra whitespace.

**Comment by mbbutler** [comment]
Is this next build fails I will boot up my linux box and run the checks locally. I'm sorry for wasting your time. I thought I could bang this out quickly from my work machine.

**Comment by wtfsck** [comment]
No need to do that, keep editing it here, it's probably the last whitespace issue. It would be better if it listed all warnings instead of just the first, though.

**Comment by wtfsck** [comment]
Thanks!

**Pull request merged**
